name: Running pipeline for script.py

on: [push, pull_request]

jobs:
  run_tests_and_style_checker:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Installing requirements from requirements.txt
        run: pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest
          pytest
      - name: Python Style Checker
        uses: andymckay/pycodestyle-action@0.1.3
  build_docker_and_publish:
    needs: [run_tests_and_style_checker]
    runs-on: [ubuntu-latest]
    env:
      LOGIN: ${{ secrets.DOCKER_USERNAME }}
      PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Logining to dockerhub
        run:  echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - uses: actions/checkout@master
      - name: Building container
        run: docker build -t $LOGIN/sites_checker -f Dockerfile .
      - name: Uploading container to dockerhub
        run: docker push $LOGIN/sites_checker
